### ISSUE TITLE
CPU Frequency change

### ISSUE THREAD

**Issue by dethmon** [Joshua-Riek/ubuntu-orange-pi5#133]
Hi, how can I change the frequency of the processor? There is no orangepi-config utility, I don't quite understand how to configure via cpufrequtils

**Comment by Joshua-Riek** [comment]
There is no orangepi-config program because this is not an Armbian-based system, I would like to create a similar utility when I have time, but I'm focused on fixing bugs at the moment.

Currently, the CPU and GPU are set to maximum performance out of the box by two systemd services. If you would like, they can be disabled with the below commands, then reboot your system to apply the changes.
```
sudo systemctl disable cpu-governor-performance
sudo systemctl disable gpu-governor-performance
```
If you would like to enable the services again, enter the below commands and reboot.
```
sudo systemctl enable cpu-governor-performance
sudo systemctl enable gpu-governor-performance
```
However, I would caution against this. The frequency scaling governor is slow to adjust the frequency under load, causing a noticeable drop in performance and micro-stuttering in some instances. 

More information about the GPU can be found in sysfs under the following path.
```bash
ubuntu@ubuntu-desktop:~$ ls /sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/
available_frequencies  cur_freq  governor  max_freq  name              power      target_freq  trans_stat
available_governors    device    load      min_freq  polling_interval  subsystem  timer        uevent
```

More information about the CPU can be found in sysfs under the following path.
```bash
ubuntu@ubuntu-desktop:~$  ls /sys/bus/cpu/devices/cpu0/cpufreq/ 
affected_cpus     cpuinfo_min_freq            scaling_available_frequencies  scaling_driver    scaling_min_freq
cpuinfo_cur_freq  cpuinfo_transition_latency  scaling_available_governors    scaling_governor  scaling_setspeed
cpuinfo_max_freq  related_cpus                scaling_cur_freq               scaling_max_freq  stats
```
