### ISSUE TITLE
An error appears when installing the Korean language pack immediately after installing Ubuntu.

### ISSUE THREAD

**Issue by ironiris** [Joshua-Riek/ubuntu-orange-pi5#21]
An error appears when installing the Korean language pack immediately after installing Ubuntu.
However,there is no problem if I install the language pack after updating the system.
![ko error1](https://user-images.githubusercontent.com/44668659/219983849-41ce4034-57cc-428f-aeae-6c44a236999d.png)
![ko error2](https://user-images.githubusercontent.com/44668659/219983852-bff6b094-a41f-464b-8e91-2963713bfdd1.png)

**Comment by Joshua-Riek** [comment]
This is normal behavior, from the error message shown I can see that apt is unable to find the Korean language packs. Using the command `apt-get update` will update the package lists and fix this issue. If you don't do it on a fresh installation, apt-get might complain that it cannot find a package in the repository, because it computed the URL based on an old version of the list (which listed an older version of the package).
