### ISSUE TITLE
GPU rasterization not on in Chromium by default

### ISSUE THREAD

**Issue by davidstoll** [Joshua-Riek/ubuntu-orange-pi5#58]
I noticed that "GPU rasterization" could be enabled in the flags option of Chromium.  Once I do that, then all but Vulcan are enabled and green.

Is there any way you could turn that on by default?  Or maybe there is a reason to keep it off?

Thanks!

**Comment by Joshua-Riek** [comment]
I could turn it on by default quite quickly. But I would be cautious, I'm not sure if it would cause issues, so I would need to look more into it as the current GPU drivers are still new and have quite a lot of bugs.

One quick example is the --no-sandbox message that pops up. If I disable the flag option for --no-sandbox Chromium GPU acceleration would break.

**Comment by diepquynh** [comment]
Does that --no-sandbox flag does something magically? Because I tried to run without it, things went fine for some time and then my OPi5 does some random freeze (the screen basically freezes, but my keyboard still responds to caps lock key somehow)

Tested on v1.8 image

**Comment by Joshua-Riek** [comment]
If I recall correctly that flag is required for the GPU to work with this version of Chromium and can cause issues when not enabled. 
I will try removing the --no-sandbox flag and see what happens, it's been a while since I tested to see what happens. But it's strange your system froze, I wonder if that flag causes some sort of memory leak if not used.

**Comment by diepquynh** [comment]
Here's what happen when I run Chromium 110 with the same flags as Chromium 91 (which was shipped with v1.8 image)
It occasionally happens, but most of the time when the screen starts freezing, it looks like this
![image](https://user-images.githubusercontent.com/13411810/224136392-2cffc13e-793b-4c17-9a87-f0eaae4b322a.png)

**Comment by Joshua-Riek** [comment]
Yeah, I have been working on upgrading the GPU drivers and Chromium version to 110. I currently use a custom version of panfork and the x11 blob so it can cause some issues with that new version of Chromium.

When using the mesa drivers from amazingfate's ppa, I have not seen any weird visual artifacts with Chromium 110. But the performance and glitches in the browser seem worse than in version 91.

**Comment by Joshua-Riek** [comment]
I updated Chromium in the latest release to version 110. There should not be any weird visual artifacts.
![Screenshot from 2023-03-10 21-04-17](https://user-images.githubusercontent.com/10427125/224428824-502f1695-315d-4725-a3f1-ad2ca2ad204c.png)

**Comment by diepquynh** [comment]
On v1.9, no issues with visual artifacts so far. However, there happens to have weird texts and component colors on several webpages like Shopee or YT (below are one of the examples, there are a lot more than that)

This issue is not there on Chromium 91. I wonder if there are changes related to Chromium renderer itself 
![image](https://user-images.githubusercontent.com/13411810/224466599-8428acb1-74b7-4bbc-a150-93cdea1dda9e.png)
![image](https://user-images.githubusercontent.com/13411810/224466643-c5b56b9d-443b-4fdc-9253-c3b5f6769296.png)

**Comment by diepquynh** [comment]
Looks like Chromium 91 was shipped with some sort of magic to work with Mali driver
![image](https://user-images.githubusercontent.com/13411810/224475049-061f73db-d99c-4bad-a581-d5ade474f21e.png)

**Comment by Joshua-Riek** [comment]
Chromium 91 is made for x11 and to be used with the blob x11 driver [here](https://github.com/Joshua-Riek/ubuntu-orange-pi5/files/10948833/libmali-valhall-g610-g6p0-x11-gbm_1.9-1_arm64.zip). I removed it in the latest update for more compatibility using wayland.
